### ISSUE TITLE
The analyzed space group by pymatgen does not match the space group the heusler or perovskite should have (225/221)

### ISSUE THREAD

**Issue by MilesZhao** [by256/icsg3d#23]
Hi there,

Thanks for your help! Now I can generate the materials of heusler and perovskite, which is great!

I generated 1000 samples and tried to understand them. Below are two examples of heusler and perovskie materials, respectively.

ex mat1:
`# generated using pymatgen
data_MgAgO3
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   4.24242926
_cell_length_b   3.87654877
_cell_length_c   3.97564435
_cell_angle_alpha   90.00000000
_cell_angle_beta   90.00000000
_cell_angle_gamma   90.00000000
_symmetry_Int_Tables_number   1
_chemical_formula_structural   MgAgO3
_chemical_formula_sum   'Mg1 Ag1 O3'
_cell_volume   65.38338299
_cell_formula_units_Z   1
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Ag  Ag0  1  0.00018641  0.00516879  0.01218479  1
  O  O1  1  -0.00928536  0.47925205  0.51363987  1
  O  O2  1  0.43859372  0.00218750  0.53234377  1
  O  O3  1  0.50947471  0.50731383  -0.00132978  1
  Mg  Mg4  1  0.46758641  0.45861037  0.47057847  1`

ex mat2:
`# generated using pymatgen
data_GdCrO2
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   3.51839519
_cell_length_b   3.70698476
_cell_length_c   3.81973004
_cell_angle_alpha   90.00000000
_cell_angle_beta   90.00000000
_cell_angle_gamma   90.00000000
_symmetry_Int_Tables_number   1
_chemical_formula_structural   GdCrO2
_chemical_formula_sum   'Gd1 Cr1 O2'
_cell_volume   49.81935364
_cell_formula_units_Z   1
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Gd  Gd0  1  0.00339958  0.00629250  0.01095058  1
  O  O1  1  0.49762579  -0.00460633  0.49799109  1
  Cr  Cr2  1  0.49284538  0.50370067  0.49876646  1
  O  O3  1  0.50543748  0.41581251  0.10943751  1`

ex mat1 is perovskite and ex mat2 is heulser.

I am not an expert in material science. When I used pymatgen to analyze their space groups, it gave me 'Pm' for ex mat2 and 'P1' for ex mat1. Does this mean the generated two materials are potential materials for heulser and perovskite? After DFT optimization, potentially they will be heulser and perovskite?

Thank you!
Yong

**Comment by cjcourt** [comment]
@MilesZhao Thanks for your question.

The space groups in the output files from `generate.py` are estimated using the pymatgen `SpaceGroupAnalyzer`. 

I am not 100% familiar with how it works but generally I would not use it as an estimate of material quality, since a space group is just a measure of symmetry, and the space group is not a defining feature of a crystal structure. 

For example, Heusler compounds appear in 3 different space groups. The foremost is the regular Heusler, X2YZ, Cu2MnAl-type compound (space group Fm3̅m). The second type is the inverse Heusler compound, Hg2CuTi type (F43m), and, finally, the XYZ MgCuSb-type half-Heusler. All three of these types of crystal structures can be encoded using a single tetrahedral unit cell in space group F43̅m. So as you can see, the space group is not fixed for a given material class.

You can see how this changes if you edit the lattice angles (parameters `alpha`, `beta` and `gamma`), in `generate.py`. For instance, if you set all three to 60 degrees, as would be common for a Heusler compound in the Tetrahedral Fm3̅m space group, you will get different results.

As for your point about if these material candidates would be feasible. It is impossible to say without further analysis, there are many many factors that should be explored for this to be determined.

Hope this helps.
CC

**Comment by MilesZhao** [comment]
thanks.
